DELETE  http://localhost:8000/products/3

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "New product again",
    "url": "web.site23",
    "price": 19.99
}


###
GET http://localhost:8000/products